comptes/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
import random, string
from .views import (
    index,
    profile,
    changer_profile,
    test,
    profile,
    ActivateAccount,
    verification_message,
    remove_user,
)



app_name = "comptes"



def generate_random():
    return ''.join(random.choice(string.ascii_lowercase + string.ascii_lowercase  + string.digits) for _ in range(64))


urlpatterns = [
    url(r"^$", index, name="index"),
    url(r"^test$", test, name="test"),
    url(r"^verification$", verification_message, name="verification_message"),
    url(r"^profile/(?P<id>[0-9a-zA-Z]*)$", profile, name="profile"),
    url(r"^profile/(?P<id>[0-9a-zA-Z]*)/edit$", changer_profile, name="changer_profile"),
    url(r"^deconnexion$", LogoutView.as_view(next_page="/"), name="deconnexion"),
    url(r"^remove_user$", remove_user, name="remove_user"),
    path(f"activation/{generate_random()}", verification_message, name="verification_message"),
    path("activer/<uidb64>/<token>/", ActivateAccount.as_view(), name="activer"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls import url, handler404, handler500
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("administration.urls", namespace="administration")),
    path("", include("comptes.urls", namespace="comptes")),
    path("reset_password/", auth_views.PasswordResetView.as_view(template_name="comptes/reset_password.html"), name="reset_password"),
    path("reset_password_sent/", auth_views.PasswordResetDoneView.as_view(template_name="comptes/password_reset_sent.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(template_name="comptes/password_reset_form.html"), name="password_reset_confirm"),
    path("reset_password_complete/", auth_views.PasswordResetCompleteView.as_view(template_name="comptes/password_reset_done.html"), name="password_reset_complete",),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
    urlpatterns += [
        url(r"^static/(?P<path>.*)/$", serve, {"document_root": settings.STATIC_ROOT,}),
    ]


handler404 = "comptes.views.view_404"

handler500 = "comptes.views.view_500"

comptes/forms.py
from django import forms
from .models import Profile, Message, Demande
import datetime


class DateInput(forms.DateInput):
    input_type = "date"


class ProfileForm(forms.ModelForm):
    class Meta:

        model = Profile
        fields = "__all__"
        exclude = ('user', 'email_confirmed')
        widgets = {
            "date_de_naissance": DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'type': 'date',
                    "min": "1960-01-01",
                    "max": str(datetime.date.today()),
                }
            ),
        }


class DemandeForm(forms.ModelForm):
    class Meta:

        model = Demande
        fields = "__all__"
        exclude = ('user', )
        widgets = {
            "date_de_retret": DateInput(
                format=('%Y-%m-%Y'),
                attrs={
                    'type': 'date',
                    "min": "1960-01-01",
                    "max": str(datetime.date.today()),
                }
            ),

        }


class MessageForm(forms.ModelForm):
    class Meta:

        model = Message
        fields = ["name", "email", "message"]


class LoginForm(forms.Form):
    login_email = forms.EmailField()
    login_password = forms.CharField(max_length=255, widget=forms.PasswordInput)


class RegistrationForm(forms.Form):
    register_email = forms.EmailField()
    register_password1 = forms.CharField(max_length=255, widget=forms.PasswordInput)
    register_password2 = forms.CharField(max_length=255, widget=forms.PasswordInput)

comptes/views.py
from django.shortcuts import render, redirect, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core import mail
from django.conf import settings
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_text
from django.utils.html import strip_tags
from django.urls import reverse
from django.template.loader import render_to_string
from django.views.generic.base import View
from django.template.loader import render_to_string
from .tokens import account_activation_token
from .forms import ProfileForm, LoginForm, RegistrationForm, MessageForm, DemandeForm
from .models import Profile, Message, Demande
import datetime
import random


def view_404(req, exption):
    return render(req, template_name="errors/404.html")


def view_500(req):
    return render(req, template_name="errors/500.html")




def index(req):
    if req.method == "POST":
        message_form = MessageForm(req.POST)
        login_form = LoginForm(req.POST)
        register_form = RegistrationForm(req.POST)
        if message_form.is_valid():
            Message.objects.create(
                name =  message_form.cleaned_data["name"],
                email = message_form.cleaned_data["email"],
                message =  message_form.cleaned_data["message"]
            )

        if login_form.is_valid():
            try:
                email = login_form.cleaned_data["login_email"]
                password = login_form.cleaned_data["login_password"]
                user_object = User.objects.get(email=email) or None
                user = authenticate(req, username=user_object.username, password=password)
                if user is not None:
                    if user.is_active:
                        login(req, user)
                        remember_me = req.POST.get("login_remember_me")
                        if not remember_me:
                            req.session.set_expiry(0)
                            req.session.modified = True
                        if user.is_superuser:
                            messages.success(
                                req, f"Bienvenue Adminstrateur !"
                            )
                            return redirect(
                                reverse("administration:control_panel")
                            )
                        elif not user.is_superuser and user.profile.email_confirmed:
                            messages.success(
                                req, f"Bienvenue {req.user.username} !"
                            )
                            return redirect(
                                reverse("comptes:profile", kwargs={"id": req.user.profile.id})
                            )
            except User.DoesNotExist:
                messages.error(
                    req, f"Cet email ou mot de pass ne correspond pas a un utilisteur"
                )



        else:
            ...

        if register_form.is_valid():
            email     = register_form.cleaned_data["register_email"]
            username  = email.strip().split('@')[0]
            password1 = register_form.cleaned_data["register_password1"]
            password2 = register_form.cleaned_data["register_password2"]

            if password1 == password2:
                user = User.objects.create_user(
                    username=username,
                    email=email,
                    password=password1,
                    is_active=False,
                )
                user.save()
                remember_me = req.POST.get("register_remember_me")
                if not remember_me:
                    req.session.set_expiry(0)
                    req.session.modified = True
                current_site = get_current_site(req)
                subject = "Activez votre compte de ESP Team"
                message = render_to_string(
                    "comptes/email_verification_template.html",
                    {
                        "user": user,
                        "domain": current_site.domain,
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "token": account_activation_token.make_token(user),
                    },
                )
                user.email_user(subject, "", html_message=message)
                messages.info(
                    req,
                    "Veuillez confirmer votre e-mail pour terminer l'inscription."
                )
                return redirect(reverse("comptes:verification_message"))
            else:
                messages.error(
                    req, f"Un probleme exist Veriver que les deux mots de passe correspondent !"
                )
    else:
        message_form = MessageForm()
        login_form = LoginForm()
        register_form = RegistrationForm()
    if req.user.is_authenticated:
        if req.user.is_superuser:
            return redirect(
                reverse("administration:control_panel")
            )
        else:
            return redirect(
                reverse("comptes:profile", kwargs={"id": req.user.profile.id})
            )
    return render(
        req,
        template_name="base.html",
        context={
            "login_form": login_form,
            "register_form": register_form,
            "message_form": message_form,
        },
    )


@login_required(login_url="/")
def changer_profile(req, id):
    profile = get_object_or_404(Profile, id=id)
    if req.method == "POST":
        form = ProfileForm(req.POST, req.FILES, instance=profile)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = profile.user
            instance.save()
    else:
        form = ProfileForm(instance=profile)
    return render(
        req, "comptes/changer_profile.html", {"form": form, "profile": profile}
    )


@login_required(login_url="/")
def profile(req, id):
    profile = get_object_or_404(Profile, id=id)
    demandes = Demande.objects.filter(user = profile.user)
    if req.method == 'POST':
        demande_form = DemandeForm(req.POST, req.FILES)
        if demande_form.is_valid():
            instance = demande_form.save(commit = False)
            instance.user = profile.user
            demande_form.save()
        else:
            messages.error(req, ("Verifier que touts les champs sont remplis"))
    else:
        demande_form = DemandeForm()
    return render(req, "comptes/profile.html", {"profile": profile, 'is_profile': True ,'demandes': demandes, 'demande_form': demande_form})

@login_required(login_url="/")
def remove_user(req):
    user = get_object_or_404(User, username=req.user.username, email=req.user.email)
    user.delete()
    return redirect(reverse('comptes:index'))


def verification_message(req):
    if req.user.is_active and req.user.profile.email_confirmed:
        return redirect(
            reverse("comptes:changer_profile", kwargs={"id": req.user.profile.id})
        )
    else:
        messages.info(
            req, ("Veuillez confirmer votre e-mail pour terminer l'inscription.")
        )
    return render(req, template_name="comptes/verification_message.html")


class ActivateAccount(View):
    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active=True
            Profile.objects.filter(user=user).update(email_confirmed=True)
            user.save()
            login(request, user)
            messages.success(request, ("Votre compte a été confirmé."))
            return redirect(
                reverse("comptes:changer_profile", kwargs={"id": user.profile.id})
            )
        else:
            messages.warning(
                request,
                (
                    "Le lien de confirmation n'était pas valide, peut-être parce qu'il a déjà été utilisé."
                )
            )
            return redirect(reverse("comptes:index"))


def test(req):
    context = {'data': req.user.id}
    return render(req, template_name="test.html", context = context)

templates/comptes/changer_profile.html
{% extends 'comptes/comptes_base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Paramètres du profile{% endblock %}
{% block content %}
<style media="screen">
  a[href^="/media/images/users"] {
    display: none;
  }
  .input:focus {
    border: 0.5px solid #797979  !important;
  }
</style>
<form class="login-form" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container-fluid rounded bg-white" style="min-height:100%">
    <div class="row" style="min-height: 800px">
      <div class="col-md-3 border-right">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
          <a class="thumbnail" href="#">
            <div class="icon-wrap" onclick="document.getElementById('file').click()" style='margin-top: 40px'>
            <img class="rounded-circle  img-responsive" width="150px" src="{{profile.image.url}}" style='cursor:pointer' id="image-change" onclick="document.getElementById('file').click()">

            </div>
            <i class='fa fa-camera font-weight-bold text-black' style='font-size:  30px; font-style:normal; color: rgba(0, 0, 0, 0.7);margin-top: -50px'></i>
            <span style="  display: none;">
              {% render_field form.image|append_attr:"class:hh" style="display: none" id="file" accept="image/*"%}
            </span>
            <div class="caption font-weight-bold text-black">{{profile.user.username}}</div>
          </a>
          <span class="text-black-50">{{profile.user.email}}</span>
        </div>
      </div>
      <div class="col-md-9 border-right">
        <div class="p-3 py-5">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <div class="d-flex justify-content-between align-items-center mb-3">
              <h4 class="text-right" style="text-align: center; color: #0094EC">Paramètres du profile</h4>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.nom.label}}</b></label>{% render_field form.nom|append_attr:"class:form-control input rounded-left" placeholder=form.nom.label %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.prenom.label}}</b></label>{% render_field form.prenom|append_attr:"class:form-control input rounded-left" placeholder=form.prenom.label %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.date_de_naissance.label}}</b></label> {% render_field form.date_de_naissance|append_attr:"class:form-control input rounded-left" value="{{profile.date_de_naissance}}" %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.pays_de_naissacne.label}}</b></label> {% render_field form.pays_de_naissacne|append_attr:"class:form-select input rounded-left" placeholder=form.pays_de_naissacne.label %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.lieu_de_naissacne.label}}</b></label> {% render_field form.lieu_de_naissacne|append_attr:"class:form-control input rounded-left" placeholder=form.lieu_de_naissacne.label %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.pays_de_residence.label}}</b></label> {% render_field form.pays_de_residence|append_attr:"class:form-select input rounded-left" placeholder=form.pays_de_residence.label %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.departement.label}}</b></label> {% render_field form.departement|append_attr:"class:form-select input rounded-left" placeholder=form.anne_universitaire.label %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.anne_universitaire.label}}</b></label> {% render_field form.anne_universitaire|append_attr:"class:form-select input rounded-left" placeholder=form.formation.label %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.formation.label}}</b></label> {% render_field form.formation|append_attr:"class:form-select input rounded-left" placeholder=form.numero_etudiant.label %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.numero_etudiant.label}}</b></label> {% render_field form.numero_etudiant|append_attr:"class:form-control input rounded-left" placeholder=form.numero_etudiant.label %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.numero_de_telephone.label}}</b></label> {% render_field form.numero_de_telephone|append_attr:"class:form-control input rounded-left" placeholder=form.numero_de_telephone.label %}</div>
            <div class="col-md-4 p-4"><label
                class="labels"><b>{{form.nom_du_personne_a_contacter.label}}</b></label>{% render_field form.nom_du_personne_a_contacter|append_attr:"class:form-control input rounded-left" placeholder=form.nom_du_personne_a_contacter.label %}</div>
            <div class="col-md-4 p-4"><label class="labels"><b>{{form.numero_du_telephone_personne_a_contacter.label}}</b></label>
              {% render_field form.numero_du_telephone_personne_a_contacter|append_attr:"class:form-control input rounded-left" placeholder=form.numero_du_telephone_personne_a_contacter.label %}</div>
          </div>
          <div class="mt-5 text-center">
            <div class="container-contact100-form-btn">
              <button class="contact100-form-btn fa fa-plus" style="border-radius:1">
                Enregister
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
</form>
{% include 'scripts.html' %}
<script type="text/javascript">
  let file = document.getElementById('file');
  file.addEventListener("change", function(e) {
    document.getElementById('image-change').setAttribute('src', URL.createObjectURL(event.target.files[0]))
  }, false);

  {% if messages %}
    {% for message in messages %}
      {% if message.tags == 'success' %}
        $.notify("{{message}}", "success");
      {% endif %}
    {% endfor %}
  {% endif %}
  $( function() {
      $( "#datepicker" ).datepicker();
    } );
</script>
{% endblock %}

templates/comptes/comptes_base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>

<html lang="en">

<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% include 'styles.html' %}
</head>

<body>


  <div class="modal fade" id="confirm-modal-delete" tabindex="-1" role="dialog" aria-labelledby="mymodalTitle" aria-hidden="true" style="z-index:4000; box-shadow:10px 10px 20px #000">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content" style="padding: 0">
        <div class="modal-header">
          <button type="button" class="close d-flex align-items-center justify-content-center" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true" class="bi bi-x"></span>
          </button>
        </div>
        <div class="modal-body p-4 p-md-5">
          <h4 class="text-center mb-4">Vouler vous confirmer</h4>
            <div class="form-group">
              <button type="submit" class="form-control btn btn-success mt-3" id="confirm-btn-delete">Confirmer</button>
              <button type="submit" class="form-control btn btn-danger mt-2" data-dismiss="modal" aria-label="Close">Annuler</button>
            </div>
        </div>
      </div>
    </div>
  </div>


  <div class="wrapper d-flex align-items-stretch"  style="min-height: 100%;">
    <nav id="sidebar">
      <div class="custom-menu">
        <button type="button" id="sidebarCollapse" class="btn btn-primary">
          <i class="fa fa-bars"></i>
          <span class="sr-only">Toggle Menu</span>
        </button>
      </div>
      <div class="p-4 pt-5">
        <div class="container mb-5" style="display:flex !important; flex-flow:column wrap; align-items:center;">
          <img class="rounded-circle" width="40px" height="40px" src="{{profile.image.url}}">
          <span class="font-weight-bold">{{profile.user.username}}</span>
          <span class="text-white-50" style="font-weight:bold">{{user.email}}</span>
        </div>
        <ul class="list-unstyled components mb-5">
          <li class="active">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-cog" id="settings-btn"></i>&nbsp;&nbsp;Paramètres</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
              {% if is_profile %}
              <li><a href="{% url 'comptes:changer_profile' profile.id %}"><i class='fa fa-edit'></i>&nbsp;&nbsp;Changer le Profile</a></li>
              {% endif %}
              <li><a href="#"><i class="fa fa-exclamation-triangle"></i>&nbsp;&nbsp;Signaler un problème</a></li>
              <li><a id="delete-account" href="#" data-toggle="modal" data-target="#confirm-modal-delete"><i class="fa fa-user-times"></i>&nbsp;&nbsp;Supprimer le compte</a></li>
            </ul>
          </li>
          {% if not is_profile %}
          <li class="nav-item"><a href="{% url 'comptes:profile' profile.id %}"><i class="bi bi-person-circle"></i>&nbsp;&nbsp;Profile</a></li>
          {% endif %}
          <li><a href="{% url 'comptes:deconnexion' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;&nbsp;Se deconnecter</a></li>
        </ul>
        <div class="footer">
          <p>
          <div class="copyright container px-4 px-lg-5">
            <div class="small text-center text-muted" style="color:#FFF !important">Copyright &copy;<br><span id="copyright"></span>-ESP Dakar</div>
          </div>
          </a>
          </p>
        </div>
      </div>
    </nav>
    <div class="table-ctn">
      <div class="container-fluid">

        {% block content %}

        {% endblock %}
      </div>

    </div>
  </div>
</body>
<script type="text/javascript">
  $('#delete-account').click(function(event) {
    event.preventDefault();
    $("#confirm-btn-delete").click(function(event) {
      window.location.href = "{% url 'comptes:remove_user' %}";
    });
  });

 $('#btn-remove-user').click(function(event) {
   event.preventDefault();
   $("#confirm-btn-delete").click(function(event) {
     window.location.href = "{% url 'comptes:remove_user' %}";
   });
 });

</script>
</html>

templates/comptes/email_verification_template.html
{% extends 'email_template.html' %}

{% block title %}Bonjour {{ user.username }}{% endblock %}
{% block instructions %}
  Veuillez cliquer sur le lien ci-dessous pour confirmer votre inscription :
{% endblock %}

{% block context %}
  {% autoescape off %}
    http://{{ domain }}{% url 'comptes:activer' uidb64=uid token=token %}
  {% endautoescape %}
{% endblock %}

{% block info %}
  Si le processus de confirmation est réussi, le lien vous mènera à votre compte
{% endblock %}

{% block end %}
  Bonne chance! Esperons que ça marche.
{% endblock %}

templates/comptes/password_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    {% include 'styles.html' %}
  </head>
  <body style="background-image: linear-gradient(to right, #2DB4FA, #0195ED)">
    {% block content %}

    {% endblock %}
  </body>
  {% include 'scripts.html' %}
</html>

templates/comptes/password_reset_done.html
{% extends 'comptes/password_base.html' %}


{% block content %}
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-body p-4 p-md-5">
      <h6>Réinitialisation du mot de passe terminé</h6>
      <hr>
        <b>Votre mot de passe a été défini. Vous pouvez aller de l'avant et vous connecter</b>
        <br>
      <a href="{% url 'comptes:index' %}">Retour à la page d'accueil</a>
    </div>
  </div>
</div>
{% endblock %}

templates/comptes/password_reset_form.html
{% extends 'comptes/password_base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-body p-4 p-md-5">
      <div class="icon d-flex align-items-center justify-content-center">
        <span class="bi bi-person-circle"></span>
      </div>
      <h1>Réinitialisation de mot de passe</h1>
      <b>
          Veuillez entrer votre nouveau mot de passe afin que nous puissions vérifier.
      </b>
        <br>
      <form  class="login-form" method="post">
        {% csrf_token %}
        <div class="form-group d-flex">
          {% render_field form.password1|append_attr:"class:form-control rounded" placeholder="Mot de passe..." %}
        </div>

        <div class="form-group d-flex">
          {% render_field form.password2|append_attr:"class:form-control rounded" placeholder="Confirmation du mot de passe..." %}
        </div>
        <div class="form-group">
          <div class="container-contact100-form-btn">
            <input type="submit" value="Envoyer un email" class="contact100-form-btn fa fa-plus btn-block" style="border-radius:5px; text-transform: capitalize" />
          </div>
        </div>
      </form>
    </div>
    <div class="modal-footer justify-content-center">
       <a href="{% url 'comptes:index' %}" >Retour à la page d'accueil</a>
    </div>
  </div>
</div>

{% endblock %}

templates/comptes/password_reset_sent.html
{% extends 'comptes/password_base.html' %}


{% block content %}
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-body p-4 p-md-5">
      <h6>Réinitialisation du mot de passe envoyée</h6>
      <hr>
        <b>Nous vous avons envoyé par e-mail des instructions pour définir votre mot de passe, si un compte existe avec l'e-mail que vous avez entré. Vous devriez les recevoir sous peu.</b><br>
        <b style="width: 60%; margin: 0 auto">Si vous ne recevez pas d'e-mail, assurez-vous d'avoir entré l'adresse avec laquelle vous vous êtes inscrit et vérifiez votre dossier de courrier indésirable.</b>
        <br>
      <a href="{% url 'comptes:index' %}">Retour à la page d'accueil</a>
    </div>
  </div>
</div>
{% endblock %}

templates/comptes/reset_password.html
{% extends 'comptes/password_base.html' %}
{% load widget_tweaks %}



{% block content %}

<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-body p-4 p-md-5">
      <div class="icon d-flex align-items-center justify-content-center">
        <span class="bi bi-person-circle"></span>
      </div>
      <b>
        Mot de passe oublié? Veuillez saisir l'adresse e-mail que vous avez utilisée pour vous inscrire
        avec nous et nous vous enverrons un lien pour réinitialiser votre mot de passe
      </b>
        <br>
      <form  class="login-form" method="post">
        {% csrf_token %}
        <div class="form-group d-flex">
          {% render_field form.email|append_attr:"class:form-control rounded" placeholder="Eamil..." %}
        </div>
        <div class="form-group">
          <div class="container-contact100-form-btn">
            <input type="submit" value="Envoyer un email" class="contact100-form-btn fa fa-plus btn-block" style="border-radius:5px; text-transform: capitalize" />
          </div>
        </div>
      </form>
    </div>
    <div class="modal-footer justify-content-center">
       <a href="{% url 'comptes:index' %}" >Retour à la page d'accueil</a>
    </div>
  </div>
</div>

{% endblock %}

templates/comptes/verification_message.html
{% extends 'comptes/password_base.html' %}
{% load widget_tweaks %}


{% block title %} Verifier votre email {% endblock %}
{% block content %}

<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-body p-4 p-md-5">
      <div class="row hide-alert">
          {% if messages %}
              <ul class="messages">
                  {% for message in messages %}
                    {% if message.tags == 'info' %}
                      {% if forloop.counter <= 2 %}
                        <li {% if message.tags %} class=" {{ message.tags}} alert alert-info" {% endif %} style="text-align:center">{{ message }}</li>
                      {% endif %}
                    {% endif %}
                  {% endfor %}
              </ul>
          {% endif %}
      </div>
    </div>
    <div class="modal-footer justify-content-center">
       <a href="{% url 'comptes:index' %}" >Retour à la page d'accueil</a>
    </div>
  </div>
</div>

{% endblock %}